# Global Values
repoUrl: 'https://github.com/badal-deep-shared/eks-blueprints-add-ons.git'
targetRevision: HEAD
region: 'ap-southeast-1'
account: '535479350247'
clusterName: 'eks-blueprints'

# Agones Values
agones:
  enable: false

# App Mesh Values
appMesh:
  enable: false

# Calico Values
calico:
  enable: false

# AWS CloudWatch Metrics Values
awsCloudWatchMetrics:
  enable: false
  serviceAccountName:

# AWS EFS CSI Driver Values
awsEfsCsiDriver:
  enable: false
  serviceAccountName:

# AWS for Fluent Bit Values
awsForFluentBit:
  enable: false
  logGroupName:
  serviceAccountName:

# AWS Load Balancer Controller Values
awsLoadBalancerController:
  enable: true
  serviceAccountName:
  podDisruptionBudget:
    maxUnavailable: 1
  image:
    repository: 602401143452.dkr.ecr.ap-southeast-1.amazonaws.com/amazon/aws-load-balancer-controller
    tag: v2.4.5
    pullPolicy: IfNotPresent

# AWS Otel Collector Values
awsOtelCollector:
  enable: false
  otlpEndpoint:
  resourceAttributes:

# Cert Manager Values
certManager:
  enable: false
  serviceAccountName:

# Cert Manager CSI Driver Values
certManagerCsiDriver:
  enable: false

# Cluster Autoscaler Values
clusterAutoscaler:
  enable: false
  serviceAccountName:
    
# Datadog Operator
datadogOperator:
  enable: false

# Strimzi Kafka Operator
strimziKafkaOperator:
  enabled: false

# External DNS Values
externalDns:
  enable: false
  serviceAccountName:
  zoneIdFilter:

# External Secrets Operator
externalSecrets:
  enable: false

# Gatekeeper Values
gatekeeper:
  enable: false
  clusterName:

# Nginx Values
ingressNginx:
  enable: false

# Grafana default Values
grafana:
  enable: false
  serviceAccount:
    create: false

# Karpenter Values
karpenter:
  enable: true
  serviceAccountName:
  controllerClusterEndpoint:
  awsDefaultInstanceProfile:

# Keda Values
keda:
  enable: false
  serviceAccountName:

# Metrics Server Values
metricsServer:
  enable: false

# Ondat Values
ondat:
  enable: false
  etcdClusterCreate: false
  serviceAccountName:
  clusterSecretRefName:
  clusterAdminUsername:
  clusterAdminPassword:
  clusterKvBackendAddress:
  clusterKvBackendTLSSecretName:
  clusterKvBackendTLSSecretNamespace:
  clusterNodeSelectorTermKey:
  clusterNodeSelectorTermValue:
  etcdNodeSelectorTermKey:
  etcdNodeSelectorTermValue:
  etcdClusterReplicas:
  etcdClusterStorageclass:
  etcdClusterStorage:

# Prometheus Values
prometheus:
  enable: true
  ampWorkspaceUrl: 'https://aps-workspaces.ap-southeast-1.amazonaws.com/workspaces/ws-a7ed3d1c-107d-4264-bc2c-fc3ca546a1dc/api/v1/remote_write'
  prometheus-node-exporter:
    tolerations:
      - key: 'karpenter'
        operator: 'Exists'
        effect: 'NoSchedule'
  server:
    remoteWrite:
      - url: 'https://aps-workspaces.ap-southeast-1.amazonaws.com/workspaces/ws-a7ed3d1c-107d-4264-bc2c-fc3ca546a1dc/api/v1/remote_write'
        sigv4:
          region: 'ap-southeast-1'
  serviceAccountName: 'amp-ingest'
  roleArn: 'arn:aws:iam::535479350247:role/eks-blueprints-amp-ingest-irsa'
  
# Metrics Server Values
sparkOperator:
  enable: false

# Tetrate Istio Values
tetrateIstio:
  enable: false
  base:
  cni:
  istiod:
  global:

# Traefik Values
traefik:
  enable: false

# VPA Values
vpa:
  enable: false

# Yunikorn Values
yunikorn:
  enable: false

# Argo Rollout Values
argoRollouts:
  enable: true

# Argo Rollout Values
argoWorkflows:
  enable: true

# Kube State Metrics Values
kubeStateMetrics:
  enable: false
  serviceAccountName:

# Kubernetes Dashboard Values
kubernetesDashboard:
  enable: false
  serviceAccountName:

# promtail Values
promtail:
  enable: false

# kubecost Values
kubecost:
  enable: true
  global:
    amp:
      enabled: true
      prometheusServerEndpoint: http://localhost:8005/workspaces/eks-blueprint-amp
      remoteWriteService: https://aps-workspaces.ap-southeast-1.amazonaws.com/workspaces/eks-blueprint-amp/api/v1/remote_write
      sigv4:
        region: ap-southeast-1

  sigV4Proxy:
    region: ap-southeast-1
    host: aps-workspaces.ap-southeast-1.amazonaws.com

# SMB CSI Driver Values
smbCsiDriver:
  enable: false

# Chaos Mesh Values
chaosMesh:
  enable: false

# Cilium Mesh Values
cilium:
  enable: true

# Reloader Values
reloader:
  enable: false

# Kube Prometheus Stack
kubePrometheusStack:
  enable: false

# Kyverno Values
kyverno:
  enable: false

policies:
  enable: false

reporter:
  enable: false
  
# NVIDIA Device Plugin Values
nvidiaDevicePlugin:
  enable: false

velero:
  enable: false
