server:
  retention: 1h
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
  global:
    scrape_interval: 15s
  nodeSelector: # <- add nodeselector, toleration and spread constraitns
    billing-team: team-riker
    type: karpenter
  tolerations:
    - key: 'karpenter'
      operator: 'Exists'
      effect: 'NoSchedule'
    - key: "billing-team"
      operator: "Equal"
      value: "team-riker"
      effect: "NoSchedule"
